version: '3'

volumes:
  django-db:

services:
  db:
    image: mysql
    container_name: django-db
    volumes:
      - django-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysitedb
      - MYSQL_ROOT_PASSWORD=888888

  web:
    build: .
    container_name: django-web
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ../myBlog:/code
    ports:
      - "8000:8000"
    links:
      - db